### ISSUE TITLE
[platform] sub-domain updates in general are not reflected in link under sharing

### ISSUE THREAD

**Issue by gabrielromk** [netzo/netzo#70]
I updated the wild-card sub-domain for a project under general and the link is not updated in the sharing view

**Comment by miguelrk** [comment]
The new deployments page should list the proper URL for each deployment. It is important to note that changing the project UID (used as a subdomain) will only apply this changes to subsequent deployments. Be this by design or a current limitation, its how this works underlyingly at the netzo infrastructure level. Also note that you can now delete old deployments altogether, in case old URLs are bothering you...
